server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://10.1.0.223:3306/backprice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gzl@admin1
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com:
      example:
        demo:
          mapper: debug
